### ISSUE TITLE
Работает ли создание тикетов из писем?

### ISSUE THREAD

**Issue by dsgolubev** [altasib/altasib.support#1]
Добрый день!

Нигде не нашел информации о том, работает ли в нем создание тикетов через почту.
Реализована ли эта функция в модуле? Если нет, то планируется ли?

**Comment by MrDeff** [comment]
Добрый день.
Пример кода есть в комментария на МП, так же у нас есть дополнительный модуль который реализует данную возможность. Поставляется клиентам на платной основе.

В публичную версию пока включать код не планируется.
